version: 2.1

jobs:
  deploy:
    docker:
      - image: tenntenn/docker-hugo-firebase:latest
    steps:
      - checkout
      - run:
          name: Install third-party dependencies
          command: git submodule sync && git submodule update --init
      - run:
          name: Build Hugo Website
          command: hugo -v
      - run:
          name: Deploy Website to Firebase Hosting
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT_ID

workflows:
  version: 2

  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main