version: 2.1

jobs:
  build:
    docker:
      - image: tenntenn/docker-hugo-firebase:latest
    working_directory: ~/my-app
    steps:
      - checkout
      - run:
          name: Install third-party dependencies
          command: git submodule sync && git submodule update --init
      - run:
          name: Build Hugo Website
          command: hugo -v
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: tenntenn/docker-hugo-firebase:latest
    working_directory: ~/my-app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Website to Firebase Hosting
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT_ID

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main